### ISSUE TITLE
Unable to build mmh3 on macOS Mojave

### ISSUE THREAD

**Issue by pramttl** [hajimes/mmh3#20] opened 2018-12-11 23:06 UTC
OS X Version: 10.14.2

```
$ pip install mmh3
Collecting mmh3
  Using cached https://files.pythonhosted.org/packages/fa/7e/3ddcab0a9fcea034212c02eb411433db9330e34d626360b97333368b4052/mmh3-2.5.1.tar.gz
Building wheels for collected packages: mmh3
  Running setup.py bdist_wheel for mmh3 ... error
  Complete output from command /Users/pranjal/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/jd/r4rs3fq51qv90t08ljqpkkhc0000gp/T/pip-install-qi111dnd/mmh3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/jd/r4rs3fq51qv90t08ljqpkkhc0000gp/T/pip-wheel-7q_m8vvr --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'mmh3' extension
  creating build
  creating build/temp.macosx-10.7-x86_64-3.6
  gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Qunused-arguments -Qunused-arguments -I/Users/pranjal/anaconda3/include/python3.6m -c mmh3module.cpp -o build/temp.macosx-10.7-x86_64-3.6/mmh3module.o
  warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  1 warning generated.
  gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Qunused-arguments -Qunused-arguments -I/Users/pranjal/anaconda3/include/python3.6m -c MurmurHash3.cpp -o build/temp.macosx-10.7-x86_64-3.6/MurmurHash3.o
  warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  1 warning generated.
  creating build/lib.macosx-10.7-x86_64-3.6
  g++ -bundle -undefined dynamic_lookup -L/Users/pranjal/anaconda3/lib -arch x86_64 -L/Users/pranjal/anaconda3/lib -arch x86_64 -Qunused-arguments -Qunused-arguments -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/mmh3module.o build/temp.macosx-10.7-x86_64-3.6/MurmurHash3.o -o build/lib.macosx-10.7-x86_64-3.6/mmh3.cpython-36m-darwin.so
  clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
  ld: library not found for -lstdc++
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command 'g++' failed with exit status 1

  ----------------------------------------
  Failed building wheel for mmh3
  Running setup.py clean for mmh3
Failed to build mmh3
Installing collected packages: mmh3
  Running setup.py install for mmh3 ... error
    Complete output from command /Users/pranjal/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/jd/r4rs3fq51qv90t08ljqpkkhc0000gp/T/pip-install-qi111dnd/mmh3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/jd/r4rs3fq51qv90t08ljqpkkhc0000gp/T/pip-record-38bwkbu3/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'mmh3' extension
    creating build
    creating build/temp.macosx-10.7-x86_64-3.6
    gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Qunused-arguments -Qunused-arguments -I/Users/pranjal/anaconda3/include/python3.6m -c mmh3module.cpp -o build/temp.macosx-10.7-x86_64-3.6/mmh3module.o
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    1 warning generated.
    gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Qunused-arguments -Qunused-arguments -I/Users/pranjal/anaconda3/include/python3.6m -c MurmurHash3.cpp -o build/temp.macosx-10.7-x86_64-3.6/MurmurHash3.o
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    1 warning generated.
    creating build/lib.macosx-10.7-x86_64-3.6
    g++ -bundle -undefined dynamic_lookup -L/Users/pranjal/anaconda3/lib -arch x86_64 -L/Users/pranjal/anaconda3/lib -arch x86_64 -Qunused-arguments -Qunused-arguments -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/mmh3module.o build/temp.macosx-10.7-x86_64-3.6/MurmurHash3.o -o build/lib.macosx-10.7-x86_64-3.6/mmh3.cpython-36m-darwin.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'g++' failed with exit status 1

    ----------------------------------------
Command "/Users/pranjal/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/jd/r4rs3fq51qv90t08ljqpkkhc0000gp/T/pip-install-qi111dnd/mmh3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/jd/r4rs3fq51qv90t08ljqpkkhc0000gp/T/pip-record-38bwkbu3/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/jd/r4rs3fq51qv90t08ljqpkkhc0000gp/T/pip-install-qi111dnd/mmh3/
```

**Comment by wotarpelo** [comment] 2018-12-19 04:50
Has anyone had any progress or idea where to resolve this issue?

    warning: include path for stdlibc++ headers not found
    pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]

The above seems to be the pinch point - but I am unfamiliar with building packages completely in Python - so I don't know where to look to find it to implement a fix. Any success or notes?

@hajimes Any tips?

**Comment by honnibal** [comment] 2018-12-19 12:22
@wotarpelo Sorry about this, we hit exactly this problem in our libraries as well. You can see how we've solved this here: https://github.com/explosion/thinc/blob/master/setup.py . Care needs to be taken to detect the *new* OSX versions, because otherwise we break our wheel building automation, which has to run on old OSX versions...Misery.

You should be able to work around the installation issue you're having in Prodigy (which I think is what uses mmh3) by cloning the mmh3 library, and applying the patch to the setup.py using the logic in Thinc's setup.py. This will let you build an sdist or wheel of mmh3. You can then pip install, so that the dependency is satisfied before you install Prodigy.

**Comment by honnibal** [comment] 2018-12-19 12:34
Just opened a PR: https://github.com/hajimes/mmh3/pull/22

You should be able to do:

```
git clone https://github.com/honnibal/mmh3
cd mmh3
python setup.py sdist
```

This should create an installable sdist for you. I don't have access to a new OSX install, so would be great to get an update on whether this works.

**Comment by wotarpelo** [comment] 2018-12-19 23:16
@honnibal Thanks very much for your help here. I've been able to build and since install all the packages with that edit implemented, however I noted on the PR there's an error thrown because of a missing import statement for sys, which you call in your regexy OS version checking (sys.platform)

Didn't want to bother creating another PR from your fork for 4 characters of code, so once that is committed that will be that, as that change I did locally had it all up and running.

(Now I just need to figure out the whole NLP thing and how to teach it to economists...)

**Comment by honnibal** [comment] 2018-12-20 00:39
Thanks, updated the PR.

**Comment by ShaktiKShrivastava** [comment] 2019-03-20 15:44
Thanks @honnibal , I’m not sure why the PR: [22](https://github.com/hajimes/mmh3/pull/22) is still open. This issue is not just limited to MacOS higher versions like Mojave, and pops up on CentOS and other distributions too. Your fix works like charm 💯

**Comment by reneeburton** [comment] 2019-05-12 20:09
also wondering why the PR is still open -- the fork worked well, but it took me a good hour of hunting and trying all sorts of other upgrades and fix before i landed here... there are a number of other libraries using this one... and so when it fails to install, they all do..  thanks much to @honnibal for removing the immediate problem.

**Comment by daturkel** [comment] 2019-06-21 17:59
Was having this issue as well. Since the original library maintainer seems to no longer support the project, I don't expect this to be merged. I was able to fix the problem in our `setup.py` by changing 
```python
requirements = [
# ...
    , 'mmh3>=2.3'	
# ...
]
```

to

```python
requirements = [
# ...
    ,  "mmh3 @ git+ssh://git@github.com/honnibal/mmh3.git@8f68a372b13b1c72da4e6a14beb559f21f5f541e",
# ...
]
```

**Comment by ryanedmundkessler** [comment] 2019-07-13 23:04
Hello, I'm also having trouble installing mmh3 on macOS Mojave. The error I'm seeing is pasted below. Can someone please outline the steps I need to take to bypass this problem? I'm having trouble following the comment thread above. 

`pip install mmh3
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting mmh3
  Using cached https://files.pythonhosted.org/packages/fa/7e/3ddcab0a9fcea034212c02eb411433db9330e34d626360b97333368b4052/mmh3-2.5.1.tar.gz
Building wheels for collected packages: mmh3
  Building wheel for mmh3 (setup.py) ... error
  ERROR: Complete output from command /anaconda2/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/55/7f9jh2q15z787ctsr2q8ys_c0000gn/T/pip-install-MNroww/mmh3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/55/7f9jh2q15z787ctsr2q8ys_c0000gn/T/pip-wheel-j0WiBM --python-tag cp27:
  ERROR: running bdist_wheel
  running build
  running build_ext
  building 'mmh3' extension
  creating build
  creating build/temp.macosx-10.6-x86_64-2.7
  llvm-gcc-4.2 -fno-strict-aliasing -I/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda2/include/python2.7 -c mmh3module.cpp -o build/temp.macosx-10.6-x86_64-2.7/mmh3module.o
  unable to execute 'llvm-gcc-4.2': No such file or directory
  error: command 'llvm-gcc-4.2' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for mmh3
  Running setup.py clean for mmh3
Failed to build mmh3
Installing collected packages: mmh3
  Running setup.py install for mmh3 ... error
    ERROR: Complete output from command /anaconda2/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/55/7f9jh2q15z787ctsr2q8ys_c0000gn/T/pip-install-MNroww/mmh3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/55/7f9jh2q15z787ctsr2q8ys_c0000gn/T/pip-record-dsFWVd/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_ext
    building 'mmh3' extension
    creating build
    creating build/temp.macosx-10.6-x86_64-2.7
    llvm-gcc-4.2 -fno-strict-aliasing -I/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda2/include/python2.7 -c mmh3module.cpp -o build/temp.macosx-10.6-x86_64-2.7/mmh3module.o
    unable to execute 'llvm-gcc-4.2': No such file or directory
    error: command 'llvm-gcc-4.2' failed with exit status 1
    ----------------------------------------
ERROR: Command "/anaconda2/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/55/7f9jh2q15z787ctsr2q8ys_c0000gn/T/pip-install-MNroww/mmh3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/55/7f9jh2q15z787ctsr2q8ys_c0000gn/T/pip-record-dsFWVd/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/55/7f9jh2q15z787ctsr2q8ys_c0000gn/T/pip-install-MNroww/mmh3/`

**Comment by hajimes** [comment] 2021-02-24 16:13
My apologies for lazy maintenance and causing inconvenience to you.

I express my gratitude to those who reported and/or tried to solve the issue, especially to @honnibal, who located the cause of the issue and offered a concrete commit.

Finally I updated mmh3 to solve the issue and will restart to maintain the library. Though recent advances in non-cryptographic hash functions saw faster/collision-less alternatives like XXH3, I hope mmh3 is still useful as @aappleby's MurmurHash3 is a now-classical, widely used algorithm and enhances interoperability across different platforms (for instance, Shodan provides MurmurHash3 values for favicons).

**Closed by hajimes** 2021-02-24 16:13 UTC
